### PR TITLE
Use `datadog-setup.php` installer

### PR DESCRIPTION
**Pull request by realFlowControl**
**Note**: This is a stacked PR on top of https://github.com/SpeedCurve-Metrics/heroku-buildpack-php-ddtrace/pull/3 ❗ 

Hey there 👋 
as stated in #3 already, this PR will move to use the `datadog-setup.php` to install the tracer, profiler and appsec. With this change, we do _not_ need to check the PHP API version anymore, as the installer will figure this out automatically.

So, this PR will
- use `datadog-setup.php` to install tracer, profiler and appsec
- add support for installing AppSec using the `DD_APPSEC_ENABLED` environment variable
- remove `DDTRACE_EXT_PHP_API` as the `datadog-setup.php` will figure this out
- rename `DDTRACE_EXT_RELEASE` to `DD_RELEASE` to follow Datadog naming schema
- rename `DDTRACE_EXT_PKG_URL` to `DD_INSTALLER_URL` (naming schema and it reflects a bit better what we are downloading)
- check if any of those "old" env variables are being used and remap / inform the user about this change or fail in case `DDTRACE_EXT_PKG_URL` is used, as it points to the wrong file anyway (currently a Debian package)
- make the buildpack dependent on PHP being around (the PHP buildback has to run first), which is stated in the `README.md` file and it will give a nice error message about this fact

I'd also like to state that a user of this Buildpack who did not set the `DDTRACE_EXT_PKG_URL` environment variable can upgrade to this new version without any friction. 

I hope you'll find this useful, I do think that migrating to the official `datadog-setup.php` makes things easier, as we'd decouple from the layout of the tarball.

This PR makes #3 obsolete, so if you might consider accepting this one, you may just close the other one (or merge both 😉)

### CODE REVIEW

**Comment by realFlowControl** [comment]
Hey @wildlyinaccurate 👋 
It looks like you did most of (if not all) the work on this buildpack. I am pinging you in case you can help me with this PR. If there is anything I can do to bring this forward, please let me know.
And thanks for setting this up 🎉

**Comment by josephwynn-sc** [comment]
Hey @realFlowControl, apologies for missing your two PRs - I accidentally had notifications turned off for this repo. Firstly, thank you so much for these changes. They look like a huge improvement to this small buildpack that I had no idea was being used by other people!

It looks to me like this is backwards compatible except for, like you say, people who use `DD_INSTALLER_URL`. Are there any other incompatible changes you can think of? If not, I am happy to merge this after some more testing.

(@wildlyinaccurate is my personal GitHub account btw, I've only recently started trying to separate my work done in a "professional context")

**Comment by realFlowControl** [comment]
Hey @josephwynn-sc,

no problem, all good. Today is a national holiday in Germany and tomorrow I have a day off. I will try this PR in some constellations on Monday and if you could I would really appreciate if you try it in your Heroku environment as well, as I have only little experience with Heroku.

I will also close the other PR on favor of this one.

Thanks a bunch
Florian

**Comment by realFlowControl** [comment]
Hey @josephwynn-sc,
I played with it again on my Heroku account and everything is looking smooth 🎉

**Comment by josephwynn-sc** [comment]
Thanks @realFlowControl! It's looking good on my end too. I'm currently in transit, but I will aim to merge before the end of the week. Thanks for your patience :)

**Comment by josephwynn-sc** [comment]
Thanks again @realFlowControl. It's very much appreciated!

**Comment by josephwynn-sc** [comment]
Hey @realFlowControl, I've just noticed that our Datadog traces no longer contain our database spans. They went missing around the time I started testing this PR, so my gut feel is it's related to these changes. Is there some extra configuration to enable collecting SQL spans again?

Screenshot 2023-08-09 at 3 45 13 PM

Edit: We just upgraded another service from the old version of this buildpack to the current one, and suddenly there are no PDO traces. Some services use mysqli and they also have no mysqli traces since upgrading.

**Comment by realFlowControl** [comment]
Hey there,
not that I am aware of. Did you install the same version of the tracer or new tracer with the new buildpack? In the later case could you try installing the older version using the new buildpack? If that does solve the issue it might be a problem in the tracer itself, otherwise it could be a problem in the buildpack.

**Comment by josephwynn-sc** [comment]
I have tried version 0.82.0 (the old default that we were using), 0.87.2 (the new default of the buildpack), and 0.90.0 (the latest version). I have also tried removing the Heroku drain for Datadog logs and adding it again. I will go through the normal channels to raise a ticket with Datadog. Thanks Florian!

**Pull request merged**
