### PR TITLE
Install latest version

### PR DESCRIPTION
**Pull request by realFlowControl**
Hey there again 👋 

I wanted to upgrade the default `DD_RELEASE` version when I thought it might be beneficial to default to the latest version, so we spare upgrading this variable with every release. I also added a note in the `README.md` stating this behaviour, so that people know they could pin to a specific version using the `DD_RELEASE` variable just in case.
What do you think?

### CODE REVIEW

**Comment by josephwynn-sc** [comment]
Thanks Florian, I think this is a good improvement.

**Comment by fernandosaguirre** [comment]
Hi guys, I don't know why, but this update broke my integration with Datadog. Traces are no longer being sent.

Any idea on what might have happened?

**Comment by realFlowControl** [comment]
Hey @fernandosaguirre,

sorry to hear this. Could you try and set the `DD_RELEASE` to whatever version you had before and see if this solves the problem? Additionally you could have a look at the `phpinfo()` output in the current version. There is a section on `ddtrace` that should give you diagnostic output.
If downgrading solves your problem please open a bug ticket in the `dd-trace-php` repo at https://github.com/DataDog/dd-trace-php/issues/new/choose

**Comment by fernandosaguirre** [comment]
@realFlowControl actually, the tracing is working. However, for some reason, the APM has stopped.

I didn't have any version set in the `DD_RELEASE` before.

**Comment by fernandosaguirre** [comment]
@realFlowControl, I managed to solve the problem by reverting to version 1.0.0 of the buildpack. To be honest, I'm not even sure why we're using this pack in the project. I wasn't the one who did the initial installation.

I noticed that the package is not mentioned in the official Datadog documentation. Can you provide me with more context on why this package is necessary for Datadog integration?

**Comment by realFlowControl** [comment]
Hey @fernandosaguirre 👋 

> I didn't have any version set in the DD_RELEASE before.

In this case you may try to set it to `0.87.2` which was the default prior to this PR.

> I managed to solve the problem by reverting to version 1.0.0 of the buildpack

Version `1.0.0` of this buildpack was using version `0.82.0` of the PHP APM, so you could pin the `DD_RELEASE` environment variable to `0.82.0` and try with this setting. This would help us find out if the problems you are experiencing are buildpack or tracer related.

> I noticed that the package is not mentioned in the official Datadog documentation.

I recently added this buildpack to the [community integrations](https://docs.datadoghq.com/developers/community/libraries/#heroku).

> Can you provide me with more context on why this package is necessary for Datadog integration?

In order to collect data from a Heroku PHP Service you need two things:
- the Datadog Agent ([installation instructions](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/))
- and the APM (tracer, profiler, appsec) which you can install through this buildback

The Datadog Agent collects data from the dyno and can act as a proxy for logs, traces, profiles, ... from the APM. This buildpack installs the tracer, profiler and appsec (which you may find over here https://github.com/DataDog/dd-trace-php/) into your dyno and enables the tracer by default (and profiling and appsec only if specified).

I hope this helps, in case you have further questions, feel also free to reach out to me or one of my colleagues via https://chat.datadoghq.com/

**Pull request merged**
